# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_window(object):
    def setupUi(self, admin_window):
        admin_window.setObjectName("admin_window")
        admin_window.resize(1286, 582)
        admin_window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(admin_window)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 0, 1021, 471))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, -20, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 85, 255);")
        self.label.setObjectName("label")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(20, 70, 221, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"border-style: outset;\n"
"color: white;\n"
"effect = QtWidgets.QGraphicsDropShadowEffect(QPushButton);\n"
"effect.setOffset(0, 0);\n"
"effect.setBlurRadius(20);\n"
"effect.setColor(QColor(57, 219, 255));\n"
"QPushButton.setGraphicsEffect(effect);\n"
"")
        self.add_btn.setObjectName("add_btn")
        self.upd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upd_btn.setGeometry(QtCore.QRect(20, 140, 221, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.upd_btn.setFont(font)
        self.upd_btn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"border-style: outset;\n"
"color: white;\n"
"effect = QtWidgets.QGraphicsDropShadowEffect(QPushButton);\n"
"effect.setOffset(0, 0);\n"
"effect.setBlurRadius(20);\n"
"effect.setColor(QColor(57, 219, 255));\n"
"QPushButton.setGraphicsEffect(effect);\n"
"")
        self.upd_btn.setObjectName("upd_btn")
        self.return_btn = QtWidgets.QPushButton(self.centralwidget)
        self.return_btn.setGeometry(QtCore.QRect(20, 210, 221, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.return_btn.setFont(font)
        self.return_btn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"border-style: outset;\n"
"color: white;\n"
"effect = QtWidgets.QGraphicsDropShadowEffect(QPushButton);\n"
"effect.setOffset(0, 0);\n"
"effect.setBlurRadius(20);\n"
"effect.setColor(QColor(57, 219, 255));\n"
"QPushButton.setGraphicsEffect(effect);\n"
"")
        self.return_btn.setObjectName("return_btn")
        admin_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(admin_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 26))
        self.menubar.setObjectName("menubar")
        admin_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(admin_window)
        self.statusbar.setObjectName("statusbar")
        admin_window.setStatusBar(self.statusbar)

        self.retranslateUi(admin_window)
        QtCore.QMetaObject.connectSlotsByName(admin_window)

    def retranslateUi(self, admin_window):
        _translate = QtCore.QCoreApplication.translate
        admin_window.setWindowTitle(_translate("admin_window", "MainWindow"))
        self.label.setText(_translate("admin_window", "Admin Mode"))
        self.add_btn.setText(_translate("admin_window", "Добавить"))
        self.upd_btn.setText(_translate("admin_window", "Обновить"))
        self.return_btn.setText(_translate("admin_window", "Выход из системы"))
