# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy_tickets_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tickets_inter(object):
    def setupUi(self, tickets_inter):
        tickets_inter.setObjectName("tickets_inter")
        tickets_inter.resize(1351, 787)
        tickets_inter.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(tickets_inter)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 10, 751, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.first_row = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.first_row.setContentsMargins(0, 0, 0, 0)
        self.first_row.setObjectName("first_row")
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.buttonGroup = QtWidgets.QButtonGroup(tickets_inter)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_10)
        self.first_row.addWidget(self.pushButton_10, 0, 9, 1, 1)
        self.pushButton7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton7.setFont(font)
        self.pushButton7.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton7.setObjectName("pushButton7")
        self.buttonGroup.addButton(self.pushButton7)
        self.first_row.addWidget(self.pushButton7, 0, 6, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton3.setFont(font)
        self.pushButton3.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 255, 127);\n"
"\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"\n"
"")
        self.pushButton3.setObjectName("pushButton3")
        self.buttonGroup.addButton(self.pushButton3)
        self.first_row.addWidget(self.pushButton3, 0, 2, 1, 1)
        self.pushButton8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton8.setFont(font)
        self.pushButton8.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton8.setObjectName("pushButton8")
        self.buttonGroup.addButton(self.pushButton8)
        self.first_row.addWidget(self.pushButton8, 0, 7, 1, 1)
        self.pushButton4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton4.setFont(font)
        self.pushButton4.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton4.setObjectName("pushButton4")
        self.buttonGroup.addButton(self.pushButton4)
        self.first_row.addWidget(self.pushButton4, 0, 3, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton2.setFont(font)
        self.pushButton2.setMouseTracking(False)
        self.pushButton2.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton2.setObjectName("pushButton2")
        self.buttonGroup.addButton(self.pushButton2)
        self.first_row.addWidget(self.pushButton2, 0, 1, 1, 1)
        self.pushButton9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton9.setFont(font)
        self.pushButton9.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton9.setObjectName("pushButton9")
        self.buttonGroup.addButton(self.pushButton9)
        self.first_row.addWidget(self.pushButton9, 0, 8, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: white;\n"
"padding: 6px;\n"
"\n"
"")
        self.pushButton1.setObjectName("pushButton1")
        self.buttonGroup.addButton(self.pushButton1)
        self.first_row.addWidget(self.pushButton1, 0, 0, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton5.setFont(font)
        self.pushButton5.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton5.setObjectName("pushButton5")
        self.buttonGroup.addButton(self.pushButton5)
        self.first_row.addWidget(self.pushButton5, 0, 4, 1, 1)
        self.pushButton6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton6.setFont(font)
        self.pushButton6.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton6.setObjectName("pushButton6")
        self.buttonGroup.addButton(self.pushButton6)
        self.first_row.addWidget(self.pushButton6, 0, 5, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.buttonGroup.addButton(self.pushButton_11)
        self.first_row.addWidget(self.pushButton_11, 0, 10, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(220, 80, 891, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.second_row = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.second_row.setContentsMargins(0, 0, 0, 0)
        self.second_row.setObjectName("second_row")
        self.pushButton18 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton18.setFont(font)
        self.pushButton18.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton18.setObjectName("pushButton18")
        self.buttonGroup.addButton(self.pushButton18)
        self.second_row.addWidget(self.pushButton18, 0, 6, 1, 1)
        self.pushButton16 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton16.setFont(font)
        self.pushButton16.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton16.setObjectName("pushButton16")
        self.buttonGroup.addButton(self.pushButton16)
        self.second_row.addWidget(self.pushButton16, 0, 4, 1, 1)
        self.pushButton23 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton23.setFont(font)
        self.pushButton23.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton23.setObjectName("pushButton23")
        self.buttonGroup.addButton(self.pushButton23)
        self.second_row.addWidget(self.pushButton23, 0, 11, 1, 1)
        self.pushButton22 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton22.setFont(font)
        self.pushButton22.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton22.setObjectName("pushButton22")
        self.buttonGroup.addButton(self.pushButton22)
        self.second_row.addWidget(self.pushButton22, 0, 10, 1, 1)
        self.pushButton21 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton21.setFont(font)
        self.pushButton21.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton21.setObjectName("pushButton21")
        self.buttonGroup.addButton(self.pushButton21)
        self.second_row.addWidget(self.pushButton21, 0, 9, 1, 1)
        self.pushButton15 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton15.setFont(font)
        self.pushButton15.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton15.setObjectName("pushButton15")
        self.buttonGroup.addButton(self.pushButton15)
        self.second_row.addWidget(self.pushButton15, 0, 3, 1, 1)
        self.pushButton20 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton20.setFont(font)
        self.pushButton20.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton20.setObjectName("pushButton20")
        self.buttonGroup.addButton(self.pushButton20)
        self.second_row.addWidget(self.pushButton20, 0, 8, 1, 1)
        self.pushButton13 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton13.setFont(font)
        self.pushButton13.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton13.setObjectName("pushButton13")
        self.buttonGroup.addButton(self.pushButton13)
        self.second_row.addWidget(self.pushButton13, 0, 1, 1, 1)
        self.pushButton19 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton19.setFont(font)
        self.pushButton19.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton19.setObjectName("pushButton19")
        self.buttonGroup.addButton(self.pushButton19)
        self.second_row.addWidget(self.pushButton19, 0, 7, 1, 1)
        self.pushButton17 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton17.setFont(font)
        self.pushButton17.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton17.setObjectName("pushButton17")
        self.buttonGroup.addButton(self.pushButton17)
        self.second_row.addWidget(self.pushButton17, 0, 5, 1, 1)
        self.pushButton12 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton12.setFont(font)
        self.pushButton12.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton12.setObjectName("pushButton12")
        self.buttonGroup.addButton(self.pushButton12)
        self.second_row.addWidget(self.pushButton12, 0, 0, 1, 1)
        self.pushButton14 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton14.setFont(font)
        self.pushButton14.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton14.setObjectName("pushButton14")
        self.buttonGroup.addButton(self.pushButton14)
        self.second_row.addWidget(self.pushButton14, 0, 2, 1, 1)
        self.pushButton24 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton24.setFont(font)
        self.pushButton24.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton24.setObjectName("pushButton24")
        self.buttonGroup.addButton(self.pushButton24)
        self.second_row.addWidget(self.pushButton24, 0, 12, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(150, 150, 1031, 481))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.others_rows = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.others_rows.setContentsMargins(0, 0, 0, 0)
        self.others_rows.setObjectName("others_rows")
        self.pushButton99_107 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_107.setFont(font)
        self.pushButton99_107.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_107.setObjectName("pushButton99_107")
        self.buttonGroup.addButton(self.pushButton99_107)
        self.others_rows.addWidget(self.pushButton99_107, 5, 12, 1, 1)
        self.pushButton99_117 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_117.setFont(font)
        self.pushButton99_117.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_117.setObjectName("pushButton99_117")
        self.buttonGroup.addButton(self.pushButton99_117)
        self.others_rows.addWidget(self.pushButton99_117, 6, 8, 1, 1)
        self.pushButton80_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton80_1.setFont(font)
        self.pushButton80_1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton80_1.setObjectName("pushButton80_1")
        self.buttonGroup.addButton(self.pushButton80_1)
        self.others_rows.addWidget(self.pushButton80_1, 3, 14, 1, 1)
        self.pushButton75 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton75.setFont(font)
        self.pushButton75.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton75.setObjectName("pushButton75")
        self.buttonGroup.addButton(self.pushButton75)
        self.others_rows.addWidget(self.pushButton75, 3, 8, 1, 1)
        self.pushButton57 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton57.setFont(font)
        self.pushButton57.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton57.setObjectName("pushButton57")
        self.buttonGroup.addButton(self.pushButton57)
        self.others_rows.addWidget(self.pushButton57, 2, 4, 1, 1)
        self.pushButton26 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton26.setFont(font)
        self.pushButton26.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton26.setObjectName("pushButton26")
        self.buttonGroup.addButton(self.pushButton26)
        self.others_rows.addWidget(self.pushButton26, 0, 1, 1, 1)
        self.pushButton99_106 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_106.setFont(font)
        self.pushButton99_106.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_106.setObjectName("pushButton99_106")
        self.buttonGroup.addButton(self.pushButton99_106)
        self.others_rows.addWidget(self.pushButton99_106, 5, 11, 1, 1)
        self.pushButton77 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton77.setFont(font)
        self.pushButton77.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton77.setObjectName("pushButton77")
        self.buttonGroup.addButton(self.pushButton77)
        self.others_rows.addWidget(self.pushButton77, 3, 10, 1, 1)
        self.pushButton87 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton87.setFont(font)
        self.pushButton87.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton87.setObjectName("pushButton87")
        self.buttonGroup.addButton(self.pushButton87)
        self.others_rows.addWidget(self.pushButton87, 4, 6, 1, 1)
        self.pushButton45 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton45.setFont(font)
        self.pushButton45.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton45.setObjectName("pushButton45")
        self.buttonGroup.addButton(self.pushButton45)
        self.others_rows.addWidget(self.pushButton45, 1, 6, 1, 1)
        self.pushButton99_108_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_108_1.setFont(font)
        self.pushButton99_108_1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_108_1.setObjectName("pushButton99_108_1")
        self.buttonGroup.addButton(self.pushButton99_108_1)
        self.others_rows.addWidget(self.pushButton99_108_1, 5, 14, 1, 1)
        self.pushButton99_122 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_122.setFont(font)
        self.pushButton99_122.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_122.setObjectName("pushButton99_122")
        self.buttonGroup.addButton(self.pushButton99_122)
        self.others_rows.addWidget(self.pushButton99_122, 6, 13, 1, 1)
        self.pushButton30 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton30.setFont(font)
        self.pushButton30.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton30.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: white;\n"
"padding: 6px;\n"
"\n"
"")
        self.pushButton30.setObjectName("pushButton30")
        self.buttonGroup.addButton(self.pushButton30)
        self.others_rows.addWidget(self.pushButton30, 0, 5, 1, 1)
        self.pushButton72 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton72.setFont(font)
        self.pushButton72.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton72.setObjectName("pushButton72")
        self.buttonGroup.addButton(self.pushButton72)
        self.others_rows.addWidget(self.pushButton72, 3, 5, 1, 1)
        self.pushButton99_110 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_110.setFont(font)
        self.pushButton99_110.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_110.setObjectName("pushButton99_110")
        self.buttonGroup.addButton(self.pushButton99_110)
        self.others_rows.addWidget(self.pushButton99_110, 6, 1, 1, 1)
        self.pushButton80 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton80.setFont(font)
        self.pushButton80.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton80.setObjectName("pushButton80")
        self.buttonGroup.addButton(self.pushButton80)
        self.others_rows.addWidget(self.pushButton80, 3, 13, 1, 1)
        self.pushButton38_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton38_1.setFont(font)
        self.pushButton38_1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton38_1.setObjectName("pushButton38_1")
        self.buttonGroup.addButton(self.pushButton38_1)
        self.others_rows.addWidget(self.pushButton38_1, 0, 14, 1, 1)
        self.pushButton99_100 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_100.setFont(font)
        self.pushButton99_100.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_100.setObjectName("pushButton99_100")
        self.buttonGroup.addButton(self.pushButton99_100)
        self.others_rows.addWidget(self.pushButton99_100, 5, 5, 1, 1)
        self.pushButton69 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton69.setFont(font)
        self.pushButton69.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton69.setObjectName("pushButton69")
        self.buttonGroup.addButton(self.pushButton69)
        self.others_rows.addWidget(self.pushButton69, 3, 2, 1, 1)
        self.pushButton99_120 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_120.setFont(font)
        self.pushButton99_120.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_120.setObjectName("pushButton99_120")
        self.buttonGroup.addButton(self.pushButton99_120)
        self.others_rows.addWidget(self.pushButton99_120, 6, 11, 1, 1)
        self.pushButton99_109 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_109.setFont(font)
        self.pushButton99_109.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_109.setObjectName("pushButton99_109")
        self.buttonGroup.addButton(self.pushButton99_109)
        self.others_rows.addWidget(self.pushButton99_109, 6, 0, 1, 1)
        self.pushButton99_104 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_104.setFont(font)
        self.pushButton99_104.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_104.setObjectName("pushButton99_104")
        self.buttonGroup.addButton(self.pushButton99_104)
        self.others_rows.addWidget(self.pushButton99_104, 5, 9, 1, 1)
        self.pushButton60 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton60.setFont(font)
        self.pushButton60.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton60.setObjectName("pushButton60")
        self.buttonGroup.addButton(self.pushButton60)
        self.others_rows.addWidget(self.pushButton60, 2, 7, 1, 1)
        self.pushButton99_118 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_118.setFont(font)
        self.pushButton99_118.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_118.setObjectName("pushButton99_118")
        self.buttonGroup.addButton(self.pushButton99_118)
        self.others_rows.addWidget(self.pushButton99_118, 6, 9, 1, 1)
        self.pushButton99_121 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_121.setFont(font)
        self.pushButton99_121.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_121.setObjectName("pushButton99_121")
        self.buttonGroup.addButton(self.pushButton99_121)
        self.others_rows.addWidget(self.pushButton99_121, 6, 12, 1, 1)
        self.pushButton39 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton39.setFont(font)
        self.pushButton39.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton39.setObjectName("pushButton39")
        self.buttonGroup.addButton(self.pushButton39)
        self.others_rows.addWidget(self.pushButton39, 1, 0, 1, 1)
        self.pushButton94_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton94_1.setFont(font)
        self.pushButton94_1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton94_1.setObjectName("pushButton94_1")
        self.buttonGroup.addButton(self.pushButton94_1)
        self.others_rows.addWidget(self.pushButton94_1, 4, 14, 1, 1)
        self.pushButton74 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton74.setFont(font)
        self.pushButton74.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton74.setObjectName("pushButton74")
        self.buttonGroup.addButton(self.pushButton74)
        self.others_rows.addWidget(self.pushButton74, 3, 7, 1, 1)
        self.pushButton43 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton43.setFont(font)
        self.pushButton43.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton43.setObjectName("pushButton43")
        self.buttonGroup.addButton(self.pushButton43)
        self.others_rows.addWidget(self.pushButton43, 1, 4, 1, 1)
        self.pushButton35 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton35.setFont(font)
        self.pushButton35.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton35.setObjectName("pushButton35")
        self.buttonGroup.addButton(self.pushButton35)
        self.others_rows.addWidget(self.pushButton35, 0, 10, 1, 1)
        self.pushButton99_115 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_115.setFont(font)
        self.pushButton99_115.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_115.setObjectName("pushButton99_115")
        self.buttonGroup.addButton(self.pushButton99_115)
        self.others_rows.addWidget(self.pushButton99_115, 6, 6, 1, 1)
        self.pushButton34 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton34.setFont(font)
        self.pushButton34.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton34.setObjectName("pushButton34")
        self.buttonGroup.addButton(self.pushButton34)
        self.others_rows.addWidget(self.pushButton34, 0, 9, 1, 1)
        self.pushButton58 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton58.setFont(font)
        self.pushButton58.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton58.setObjectName("pushButton58")
        self.buttonGroup.addButton(self.pushButton58)
        self.others_rows.addWidget(self.pushButton58, 2, 5, 1, 1)
        self.pushButton70 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton70.setFont(font)
        self.pushButton70.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton70.setObjectName("pushButton70")
        self.buttonGroup.addButton(self.pushButton70)
        self.others_rows.addWidget(self.pushButton70, 3, 3, 1, 1)
        self.pushButton93 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton93.setFont(font)
        self.pushButton93.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton93.setObjectName("pushButton93")
        self.buttonGroup.addButton(self.pushButton93)
        self.others_rows.addWidget(self.pushButton93, 4, 12, 1, 1)
        self.pushButton27 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton27.setFont(font)
        self.pushButton27.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton27.setObjectName("pushButton27")
        self.buttonGroup.addButton(self.pushButton27)
        self.others_rows.addWidget(self.pushButton27, 0, 2, 1, 1)
        self.pushButton25 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton25.setFont(font)
        self.pushButton25.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton25.setObjectName("pushButton25")
        self.buttonGroup.addButton(self.pushButton25)
        self.others_rows.addWidget(self.pushButton25, 0, 0, 1, 1)
        self.pushButton48 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton48.setFont(font)
        self.pushButton48.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton48.setObjectName("pushButton48")
        self.buttonGroup.addButton(self.pushButton48)
        self.others_rows.addWidget(self.pushButton48, 1, 9, 1, 1)
        self.pushButton42 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton42.setFont(font)
        self.pushButton42.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton42.setObjectName("pushButton42")
        self.buttonGroup.addButton(self.pushButton42)
        self.others_rows.addWidget(self.pushButton42, 1, 3, 1, 1)
        self.pushButton95 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton95.setFont(font)
        self.pushButton95.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton95.setObjectName("pushButton95")
        self.buttonGroup.addButton(self.pushButton95)
        self.others_rows.addWidget(self.pushButton95, 5, 0, 1, 1)
        self.pushButton31 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton31.setFont(font)
        self.pushButton31.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton31.setObjectName("pushButton31")
        self.buttonGroup.addButton(self.pushButton31)
        self.others_rows.addWidget(self.pushButton31, 0, 6, 1, 1)
        self.pushButton54 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton54.setFont(font)
        self.pushButton54.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton54.setObjectName("pushButton54")
        self.buttonGroup.addButton(self.pushButton54)
        self.others_rows.addWidget(self.pushButton54, 2, 1, 1, 1)
        self.pushButton94 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton94.setFont(font)
        self.pushButton94.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton94.setObjectName("pushButton94")
        self.buttonGroup.addButton(self.pushButton94)
        self.others_rows.addWidget(self.pushButton94, 4, 13, 1, 1)
        self.pushButton79 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton79.setFont(font)
        self.pushButton79.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton79.setObjectName("pushButton79")
        self.buttonGroup.addButton(self.pushButton79)
        self.others_rows.addWidget(self.pushButton79, 3, 12, 1, 1)
        self.pushButton37 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton37.setFont(font)
        self.pushButton37.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton37.setObjectName("pushButton37")
        self.buttonGroup.addButton(self.pushButton37)
        self.others_rows.addWidget(self.pushButton37, 0, 12, 1, 1)
        self.pushButton47 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton47.setFont(font)
        self.pushButton47.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton47.setObjectName("pushButton47")
        self.buttonGroup.addButton(self.pushButton47)
        self.others_rows.addWidget(self.pushButton47, 1, 8, 1, 1)
        self.pushButton50 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton50.setFont(font)
        self.pushButton50.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton50.setObjectName("pushButton50")
        self.buttonGroup.addButton(self.pushButton50)
        self.others_rows.addWidget(self.pushButton50, 1, 11, 1, 1)
        self.pushButton97 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton97.setFont(font)
        self.pushButton97.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton97.setObjectName("pushButton97")
        self.buttonGroup.addButton(self.pushButton97)
        self.others_rows.addWidget(self.pushButton97, 5, 2, 1, 1)
        self.pushButton66 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton66.setFont(font)
        self.pushButton66.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton66.setObjectName("pushButton66")
        self.buttonGroup.addButton(self.pushButton66)
        self.others_rows.addWidget(self.pushButton66, 2, 13, 1, 1)
        self.pushButton99_103 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_103.setFont(font)
        self.pushButton99_103.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_103.setObjectName("pushButton99_103")
        self.buttonGroup.addButton(self.pushButton99_103)
        self.others_rows.addWidget(self.pushButton99_103, 5, 8, 1, 1)
        self.pushButton51 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton51.setFont(font)
        self.pushButton51.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton51.setObjectName("pushButton51")
        self.buttonGroup.addButton(self.pushButton51)
        self.others_rows.addWidget(self.pushButton51, 1, 12, 1, 1)
        self.pushButton92 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton92.setFont(font)
        self.pushButton92.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton92.setObjectName("pushButton92")
        self.buttonGroup.addButton(self.pushButton92)
        self.others_rows.addWidget(self.pushButton92, 4, 11, 1, 1)
        self.pushButton99_101 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_101.setFont(font)
        self.pushButton99_101.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_101.setObjectName("pushButton99_101")
        self.buttonGroup.addButton(self.pushButton99_101)
        self.others_rows.addWidget(self.pushButton99_101, 5, 6, 1, 1)
        self.pushButton71 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton71.setFont(font)
        self.pushButton71.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton71.setObjectName("pushButton71")
        self.buttonGroup.addButton(self.pushButton71)
        self.others_rows.addWidget(self.pushButton71, 3, 4, 1, 1)
        self.pushButton99_108 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_108.setFont(font)
        self.pushButton99_108.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_108.setObjectName("pushButton99_108")
        self.buttonGroup.addButton(self.pushButton99_108)
        self.others_rows.addWidget(self.pushButton99_108, 5, 13, 1, 1)
        self.pushButton65 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton65.setFont(font)
        self.pushButton65.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton65.setObjectName("pushButton65")
        self.buttonGroup.addButton(self.pushButton65)
        self.others_rows.addWidget(self.pushButton65, 2, 12, 1, 1)
        self.pushButton33 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton33.setFont(font)
        self.pushButton33.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton33.setObjectName("pushButton33")
        self.buttonGroup.addButton(self.pushButton33)
        self.others_rows.addWidget(self.pushButton33, 0, 8, 1, 1)
        self.pushButton52 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton52.setFont(font)
        self.pushButton52.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton52.setObjectName("pushButton52")
        self.buttonGroup.addButton(self.pushButton52)
        self.others_rows.addWidget(self.pushButton52, 1, 13, 1, 1)
        self.pushButton99_105 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_105.setFont(font)
        self.pushButton99_105.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_105.setObjectName("pushButton99_105")
        self.buttonGroup.addButton(self.pushButton99_105)
        self.others_rows.addWidget(self.pushButton99_105, 5, 10, 1, 1)
        self.pushButton78 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton78.setFont(font)
        self.pushButton78.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton78.setObjectName("pushButton78")
        self.buttonGroup.addButton(self.pushButton78)
        self.others_rows.addWidget(self.pushButton78, 3, 11, 1, 1)
        self.pushButton62 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton62.setFont(font)
        self.pushButton62.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton62.setObjectName("pushButton62")
        self.buttonGroup.addButton(self.pushButton62)
        self.others_rows.addWidget(self.pushButton62, 2, 9, 1, 1)
        self.pushButton85 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton85.setFont(font)
        self.pushButton85.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton85.setObjectName("pushButton85")
        self.buttonGroup.addButton(self.pushButton85)
        self.others_rows.addWidget(self.pushButton85, 4, 4, 1, 1)
        self.pushButton99_113 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_113.setFont(font)
        self.pushButton99_113.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_113.setObjectName("pushButton99_113")
        self.buttonGroup.addButton(self.pushButton99_113)
        self.others_rows.addWidget(self.pushButton99_113, 6, 4, 1, 1)
        self.pushButton44 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton44.setFont(font)
        self.pushButton44.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton44.setObjectName("pushButton44")
        self.buttonGroup.addButton(self.pushButton44)
        self.others_rows.addWidget(self.pushButton44, 1, 5, 1, 1)
        self.pushButton49 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton49.setFont(font)
        self.pushButton49.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton49.setObjectName("pushButton49")
        self.buttonGroup.addButton(self.pushButton49)
        self.others_rows.addWidget(self.pushButton49, 1, 10, 1, 1)
        self.pushButton99_123 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_123.setFont(font)
        self.pushButton99_123.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_123.setObjectName("pushButton99_123")
        self.buttonGroup.addButton(self.pushButton99_123)
        self.others_rows.addWidget(self.pushButton99_123, 6, 14, 1, 1)
        self.pushButton28 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton28.setFont(font)
        self.pushButton28.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"border: none;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton28.setObjectName("pushButton28")
        self.buttonGroup.addButton(self.pushButton28)
        self.others_rows.addWidget(self.pushButton28, 0, 3, 1, 1)
        self.pushButton89 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton89.setFont(font)
        self.pushButton89.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton89.setObjectName("pushButton89")
        self.buttonGroup.addButton(self.pushButton89)
        self.others_rows.addWidget(self.pushButton89, 4, 8, 1, 1)
        self.pushButton76 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton76.setFont(font)
        self.pushButton76.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton76.setObjectName("pushButton76")
        self.buttonGroup.addButton(self.pushButton76)
        self.others_rows.addWidget(self.pushButton76, 3, 9, 1, 1)
        self.pushButton73 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton73.setFont(font)
        self.pushButton73.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton73.setObjectName("pushButton73")
        self.buttonGroup.addButton(self.pushButton73)
        self.others_rows.addWidget(self.pushButton73, 3, 6, 1, 1)
        self.pushButton99 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99.setFont(font)
        self.pushButton99.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99.setObjectName("pushButton99")
        self.buttonGroup.addButton(self.pushButton99)
        self.others_rows.addWidget(self.pushButton99, 5, 4, 1, 1)
        self.pushButton46 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton46.setFont(font)
        self.pushButton46.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton46.setObjectName("pushButton46")
        self.buttonGroup.addButton(self.pushButton46)
        self.others_rows.addWidget(self.pushButton46, 1, 7, 1, 1)
        self.pushButton67 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton67.setFont(font)
        self.pushButton67.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton67.setObjectName("pushButton67")
        self.buttonGroup.addButton(self.pushButton67)
        self.others_rows.addWidget(self.pushButton67, 3, 0, 1, 1)
        self.pushButton61 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton61.setFont(font)
        self.pushButton61.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton61.setObjectName("pushButton61")
        self.buttonGroup.addButton(self.pushButton61)
        self.others_rows.addWidget(self.pushButton61, 2, 8, 1, 1)
        self.pushButton91 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton91.setFont(font)
        self.pushButton91.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton91.setObjectName("pushButton91")
        self.buttonGroup.addButton(self.pushButton91)
        self.others_rows.addWidget(self.pushButton91, 4, 10, 1, 1)
        self.pushButton55 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton55.setFont(font)
        self.pushButton55.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton55.setObjectName("pushButton55")
        self.buttonGroup.addButton(self.pushButton55)
        self.others_rows.addWidget(self.pushButton55, 2, 2, 1, 1)
        self.pushButton96 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton96.setFont(font)
        self.pushButton96.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton96.setObjectName("pushButton96")
        self.buttonGroup.addButton(self.pushButton96)
        self.others_rows.addWidget(self.pushButton96, 5, 1, 1, 1)
        self.pushButton99_111 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_111.setFont(font)
        self.pushButton99_111.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_111.setObjectName("pushButton99_111")
        self.buttonGroup.addButton(self.pushButton99_111)
        self.others_rows.addWidget(self.pushButton99_111, 6, 2, 1, 1)
        self.pushButton53 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton53.setFont(font)
        self.pushButton53.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton53.setObjectName("pushButton53")
        self.buttonGroup.addButton(self.pushButton53)
        self.others_rows.addWidget(self.pushButton53, 2, 0, 1, 1)
        self.pushButton99_102 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_102.setFont(font)
        self.pushButton99_102.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_102.setObjectName("pushButton99_102")
        self.buttonGroup.addButton(self.pushButton99_102)
        self.others_rows.addWidget(self.pushButton99_102, 5, 7, 1, 1)
        self.pushButton64 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton64.setFont(font)
        self.pushButton64.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton64.setObjectName("pushButton64")
        self.buttonGroup.addButton(self.pushButton64)
        self.others_rows.addWidget(self.pushButton64, 2, 11, 1, 1)
        self.pushButton41 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton41.setFont(font)
        self.pushButton41.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton41.setObjectName("pushButton41")
        self.buttonGroup.addButton(self.pushButton41)
        self.others_rows.addWidget(self.pushButton41, 1, 2, 1, 1)
        self.pushButton38 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton38.setFont(font)
        self.pushButton38.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton38.setObjectName("pushButton38")
        self.buttonGroup.addButton(self.pushButton38)
        self.others_rows.addWidget(self.pushButton38, 0, 13, 1, 1)
        self.pushButton29 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton29.setFont(font)
        self.pushButton29.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: white;\n"
"padding: 6px;\n"
"\n"
"")
        self.pushButton29.setObjectName("pushButton29")
        self.buttonGroup.addButton(self.pushButton29)
        self.others_rows.addWidget(self.pushButton29, 0, 4, 1, 1)
        self.pushButton90 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton90.setFont(font)
        self.pushButton90.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton90.setObjectName("pushButton90")
        self.buttonGroup.addButton(self.pushButton90)
        self.others_rows.addWidget(self.pushButton90, 4, 9, 1, 1)
        self.pushButton88 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton88.setFont(font)
        self.pushButton88.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton88.setObjectName("pushButton88")
        self.buttonGroup.addButton(self.pushButton88)
        self.others_rows.addWidget(self.pushButton88, 4, 7, 1, 1)
        self.pushButton82 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton82.setFont(font)
        self.pushButton82.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton82.setObjectName("pushButton82")
        self.buttonGroup.addButton(self.pushButton82)
        self.others_rows.addWidget(self.pushButton82, 4, 1, 1, 1)
        self.pushButton59 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton59.setFont(font)
        self.pushButton59.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton59.setObjectName("pushButton59")
        self.buttonGroup.addButton(self.pushButton59)
        self.others_rows.addWidget(self.pushButton59, 2, 6, 1, 1)
        self.pushButton36 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton36.setFont(font)
        self.pushButton36.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton36.setObjectName("pushButton36")
        self.buttonGroup.addButton(self.pushButton36)
        self.others_rows.addWidget(self.pushButton36, 0, 11, 1, 1)
        self.pushButton32 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton32.setFont(font)
        self.pushButton32.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton32.setObjectName("pushButton32")
        self.buttonGroup.addButton(self.pushButton32)
        self.others_rows.addWidget(self.pushButton32, 0, 7, 1, 1)
        self.pushButton81 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton81.setFont(font)
        self.pushButton81.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton81.setObjectName("pushButton81")
        self.buttonGroup.addButton(self.pushButton81)
        self.others_rows.addWidget(self.pushButton81, 4, 0, 1, 1)
        self.pushButton86 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton86.setFont(font)
        self.pushButton86.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton86.setObjectName("pushButton86")
        self.buttonGroup.addButton(self.pushButton86)
        self.others_rows.addWidget(self.pushButton86, 4, 5, 1, 1)
        self.pushButton66_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton66_1.setFont(font)
        self.pushButton66_1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton66_1.setObjectName("pushButton66_1")
        self.buttonGroup.addButton(self.pushButton66_1)
        self.others_rows.addWidget(self.pushButton66_1, 2, 14, 1, 1)
        self.pushButton98 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton98.setFont(font)
        self.pushButton98.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton98.setObjectName("pushButton98")
        self.buttonGroup.addButton(self.pushButton98)
        self.others_rows.addWidget(self.pushButton98, 5, 3, 1, 1)
        self.pushButton99_112 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_112.setFont(font)
        self.pushButton99_112.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_112.setObjectName("pushButton99_112")
        self.buttonGroup.addButton(self.pushButton99_112)
        self.others_rows.addWidget(self.pushButton99_112, 6, 3, 1, 1)
        self.pushButton68 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton68.setFont(font)
        self.pushButton68.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton68.setObjectName("pushButton68")
        self.buttonGroup.addButton(self.pushButton68)
        self.others_rows.addWidget(self.pushButton68, 3, 1, 1, 1)
        self.pushButton52_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton52_1.setFont(font)
        self.pushButton52_1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton52_1.setObjectName("pushButton52_1")
        self.buttonGroup.addButton(self.pushButton52_1)
        self.others_rows.addWidget(self.pushButton52_1, 1, 14, 1, 1)
        self.pushButton84 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton84.setFont(font)
        self.pushButton84.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton84.setObjectName("pushButton84")
        self.buttonGroup.addButton(self.pushButton84)
        self.others_rows.addWidget(self.pushButton84, 4, 3, 1, 1)
        self.pushButton99_114 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_114.setFont(font)
        self.pushButton99_114.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_114.setObjectName("pushButton99_114")
        self.buttonGroup.addButton(self.pushButton99_114)
        self.others_rows.addWidget(self.pushButton99_114, 6, 5, 1, 1)
        self.pushButton56 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton56.setFont(font)
        self.pushButton56.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton56.setObjectName("pushButton56")
        self.buttonGroup.addButton(self.pushButton56)
        self.others_rows.addWidget(self.pushButton56, 2, 3, 1, 1)
        self.pushButton99_119 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_119.setFont(font)
        self.pushButton99_119.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_119.setObjectName("pushButton99_119")
        self.buttonGroup.addButton(self.pushButton99_119)
        self.others_rows.addWidget(self.pushButton99_119, 6, 10, 1, 1)
        self.pushButton63 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton63.setFont(font)
        self.pushButton63.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton63.setObjectName("pushButton63")
        self.buttonGroup.addButton(self.pushButton63)
        self.others_rows.addWidget(self.pushButton63, 2, 10, 1, 1)
        self.pushButton83 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton83.setFont(font)
        self.pushButton83.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton83.setObjectName("pushButton83")
        self.buttonGroup.addButton(self.pushButton83)
        self.others_rows.addWidget(self.pushButton83, 4, 2, 1, 1)
        self.pushButton99_116 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton99_116.setFont(font)
        self.pushButton99_116.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton99_116.setObjectName("pushButton99_116")
        self.buttonGroup.addButton(self.pushButton99_116)
        self.others_rows.addWidget(self.pushButton99_116, 6, 7, 1, 1)
        self.pushButton40 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton40.setFont(font)
        self.pushButton40.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton40.setObjectName("pushButton40")
        self.buttonGroup.addButton(self.pushButton40)
        self.others_rows.addWidget(self.pushButton40, 1, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 111, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1180, 10, 111, 621))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.pushButton_176 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_176.setGeometry(QtCore.QRect(40, 660, 62, 52))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_176.setFont(font)
        self.pushButton_176.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton_176.setText("")
        self.pushButton_176.setObjectName("pushButton_176")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(110, 670, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setGeometry(QtCore.QRect(250, 660, 62, 56))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: white;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"border-style: outset;\n"
"")
        self.pushButton_40.setText("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(320, 670, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setGeometry(QtCore.QRect(450, 660, 62, 52))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet("background-color: red;\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"")
        self.pushButton_41.setText("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(530, 670, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setEnabled(False)
        self.next_btn.setGeometry(QtCore.QRect(770, 660, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"border-style: outset;\n"
"color: white;\n"
"effect = QtWidgets.QGraphicsDropShadowEffect(QPushButton);\n"
"effect.setOffset(0, 0);\n"
"effect.setBlurRadius(20);\n"
"effect.setColor(QColor(57, 219, 255));\n"
"QPushButton.setGraphicsEffect(effect);\n"
"")
        self.next_btn.setObjectName("next_btn")
        tickets_inter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(tickets_inter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1351, 26))
        self.menubar.setObjectName("menubar")
        tickets_inter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(tickets_inter)
        self.statusbar.setObjectName("statusbar")
        tickets_inter.setStatusBar(self.statusbar)

        self.retranslateUi(tickets_inter)
        QtCore.QMetaObject.connectSlotsByName(tickets_inter)

    def retranslateUi(self, tickets_inter):
        _translate = QtCore.QCoreApplication.translate
        tickets_inter.setWindowTitle(_translate("tickets_inter", "MainWindow"))
        self.pushButton_10.setText(_translate("tickets_inter", "10"))
        self.pushButton7.setText(_translate("tickets_inter", "7"))
        self.pushButton3.setText(_translate("tickets_inter", "3"))
        self.pushButton8.setText(_translate("tickets_inter", "8"))
        self.pushButton4.setText(_translate("tickets_inter", "4"))
        self.pushButton2.setText(_translate("tickets_inter", "2"))
        self.pushButton9.setText(_translate("tickets_inter", "9"))
        self.pushButton1.setText(_translate("tickets_inter", "1"))
        self.pushButton5.setText(_translate("tickets_inter", "5"))
        self.pushButton6.setText(_translate("tickets_inter", "6"))
        self.pushButton_11.setText(_translate("tickets_inter", "11"))
        self.pushButton18.setText(_translate("tickets_inter", "7"))
        self.pushButton16.setText(_translate("tickets_inter", "5"))
        self.pushButton23.setText(_translate("tickets_inter", "12"))
        self.pushButton22.setText(_translate("tickets_inter", "11"))
        self.pushButton21.setText(_translate("tickets_inter", "10"))
        self.pushButton15.setText(_translate("tickets_inter", "4"))
        self.pushButton20.setText(_translate("tickets_inter", "9"))
        self.pushButton13.setText(_translate("tickets_inter", "2"))
        self.pushButton19.setText(_translate("tickets_inter", "8"))
        self.pushButton17.setText(_translate("tickets_inter", "6"))
        self.pushButton12.setText(_translate("tickets_inter", "1"))
        self.pushButton14.setText(_translate("tickets_inter", "3"))
        self.pushButton24.setText(_translate("tickets_inter", "13"))
        self.pushButton99_107.setText(_translate("tickets_inter", "13"))
        self.pushButton99_117.setText(_translate("tickets_inter", "9"))
        self.pushButton80_1.setText(_translate("tickets_inter", "15"))
        self.pushButton75.setText(_translate("tickets_inter", "9"))
        self.pushButton57.setText(_translate("tickets_inter", "5"))
        self.pushButton26.setText(_translate("tickets_inter", "2"))
        self.pushButton99_106.setText(_translate("tickets_inter", "12"))
        self.pushButton77.setText(_translate("tickets_inter", "11"))
        self.pushButton87.setText(_translate("tickets_inter", "7"))
        self.pushButton45.setText(_translate("tickets_inter", "7"))
        self.pushButton99_108_1.setText(_translate("tickets_inter", "15"))
        self.pushButton99_122.setText(_translate("tickets_inter", "14"))
        self.pushButton30.setText(_translate("tickets_inter", "6"))
        self.pushButton72.setText(_translate("tickets_inter", "6"))
        self.pushButton99_110.setText(_translate("tickets_inter", "2"))
        self.pushButton80.setText(_translate("tickets_inter", "14"))
        self.pushButton38_1.setText(_translate("tickets_inter", "15"))
        self.pushButton99_100.setText(_translate("tickets_inter", "6"))
        self.pushButton69.setText(_translate("tickets_inter", "3"))
        self.pushButton99_120.setText(_translate("tickets_inter", "12"))
        self.pushButton99_109.setText(_translate("tickets_inter", "1"))
        self.pushButton99_104.setText(_translate("tickets_inter", "10"))
        self.pushButton60.setText(_translate("tickets_inter", "8"))
        self.pushButton99_118.setText(_translate("tickets_inter", "10"))
        self.pushButton99_121.setText(_translate("tickets_inter", "13"))
        self.pushButton39.setText(_translate("tickets_inter", "1"))
        self.pushButton94_1.setText(_translate("tickets_inter", "15"))
        self.pushButton74.setText(_translate("tickets_inter", "8"))
        self.pushButton43.setText(_translate("tickets_inter", "5"))
        self.pushButton35.setText(_translate("tickets_inter", "11"))
        self.pushButton99_115.setText(_translate("tickets_inter", "7"))
        self.pushButton34.setText(_translate("tickets_inter", "10"))
        self.pushButton58.setText(_translate("tickets_inter", "6"))
        self.pushButton70.setText(_translate("tickets_inter", "4"))
        self.pushButton93.setText(_translate("tickets_inter", "13"))
        self.pushButton27.setText(_translate("tickets_inter", "3"))
        self.pushButton25.setText(_translate("tickets_inter", "1"))
        self.pushButton48.setText(_translate("tickets_inter", "10"))
        self.pushButton42.setText(_translate("tickets_inter", "4"))
        self.pushButton95.setText(_translate("tickets_inter", "1"))
        self.pushButton31.setText(_translate("tickets_inter", "7"))
        self.pushButton54.setText(_translate("tickets_inter", "2"))
        self.pushButton94.setText(_translate("tickets_inter", "14"))
        self.pushButton79.setText(_translate("tickets_inter", "13"))
        self.pushButton37.setText(_translate("tickets_inter", "13"))
        self.pushButton47.setText(_translate("tickets_inter", "9"))
        self.pushButton50.setText(_translate("tickets_inter", "12"))
        self.pushButton97.setText(_translate("tickets_inter", "3"))
        self.pushButton66.setText(_translate("tickets_inter", "14"))
        self.pushButton99_103.setText(_translate("tickets_inter", "9"))
        self.pushButton51.setText(_translate("tickets_inter", "13"))
        self.pushButton92.setText(_translate("tickets_inter", "12"))
        self.pushButton99_101.setText(_translate("tickets_inter", "7"))
        self.pushButton71.setText(_translate("tickets_inter", "5"))
        self.pushButton99_108.setText(_translate("tickets_inter", "14"))
        self.pushButton65.setText(_translate("tickets_inter", "13"))
        self.pushButton33.setText(_translate("tickets_inter", "9"))
        self.pushButton52.setText(_translate("tickets_inter", "14"))
        self.pushButton99_105.setText(_translate("tickets_inter", "11"))
        self.pushButton78.setText(_translate("tickets_inter", "12"))
        self.pushButton62.setText(_translate("tickets_inter", "10"))
        self.pushButton85.setText(_translate("tickets_inter", "5"))
        self.pushButton99_113.setText(_translate("tickets_inter", "5"))
        self.pushButton44.setText(_translate("tickets_inter", "6"))
        self.pushButton49.setText(_translate("tickets_inter", "11"))
        self.pushButton99_123.setText(_translate("tickets_inter", "15"))
        self.pushButton28.setText(_translate("tickets_inter", "4"))
        self.pushButton89.setText(_translate("tickets_inter", "9"))
        self.pushButton76.setText(_translate("tickets_inter", "10"))
        self.pushButton73.setText(_translate("tickets_inter", "7"))
        self.pushButton99.setText(_translate("tickets_inter", "5"))
        self.pushButton46.setText(_translate("tickets_inter", "8"))
        self.pushButton67.setText(_translate("tickets_inter", "1"))
        self.pushButton61.setText(_translate("tickets_inter", "9"))
        self.pushButton91.setText(_translate("tickets_inter", "11"))
        self.pushButton55.setText(_translate("tickets_inter", "3"))
        self.pushButton96.setText(_translate("tickets_inter", "2"))
        self.pushButton99_111.setText(_translate("tickets_inter", "3"))
        self.pushButton53.setText(_translate("tickets_inter", "1"))
        self.pushButton99_102.setText(_translate("tickets_inter", "8"))
        self.pushButton64.setText(_translate("tickets_inter", "12"))
        self.pushButton41.setText(_translate("tickets_inter", "3"))
        self.pushButton38.setText(_translate("tickets_inter", "14"))
        self.pushButton29.setText(_translate("tickets_inter", "5"))
        self.pushButton90.setText(_translate("tickets_inter", "10"))
        self.pushButton88.setText(_translate("tickets_inter", "8"))
        self.pushButton82.setText(_translate("tickets_inter", "2"))
        self.pushButton59.setText(_translate("tickets_inter", "7"))
        self.pushButton36.setText(_translate("tickets_inter", "12"))
        self.pushButton32.setText(_translate("tickets_inter", "8"))
        self.pushButton81.setText(_translate("tickets_inter", "1"))
        self.pushButton86.setText(_translate("tickets_inter", "6"))
        self.pushButton66_1.setText(_translate("tickets_inter", "15"))
        self.pushButton98.setText(_translate("tickets_inter", "4"))
        self.pushButton99_112.setText(_translate("tickets_inter", "4"))
        self.pushButton68.setText(_translate("tickets_inter", "2"))
        self.pushButton52_1.setText(_translate("tickets_inter", "15"))
        self.pushButton84.setText(_translate("tickets_inter", "4"))
        self.pushButton99_114.setText(_translate("tickets_inter", "6"))
        self.pushButton56.setText(_translate("tickets_inter", "4"))
        self.pushButton99_119.setText(_translate("tickets_inter", "11"))
        self.pushButton63.setText(_translate("tickets_inter", "11"))
        self.pushButton83.setText(_translate("tickets_inter", "3"))
        self.pushButton99_116.setText(_translate("tickets_inter", "8"))
        self.pushButton40.setText(_translate("tickets_inter", "2"))
        self.label.setText(_translate("tickets_inter", "     1"))
        self.label_9.setText(_translate("tickets_inter", "     2"))
        self.label_8.setText(_translate("tickets_inter", "     3"))
        self.label_7.setText(_translate("tickets_inter", "     4"))
        self.label_6.setText(_translate("tickets_inter", "     5"))
        self.label_5.setText(_translate("tickets_inter", "     6"))
        self.label_3.setText(_translate("tickets_inter", "     7"))
        self.label_4.setText(_translate("tickets_inter", "     8"))
        self.label_2.setText(_translate("tickets_inter", "     9"))
        self.label_10.setText(_translate("tickets_inter", "   1"))
        self.label_11.setText(_translate("tickets_inter", "   2"))
        self.label_12.setText(_translate("tickets_inter", "   3"))
        self.label_13.setText(_translate("tickets_inter", "   4"))
        self.label_14.setText(_translate("tickets_inter", "   5"))
        self.label_15.setText(_translate("tickets_inter", "   6"))
        self.label_16.setText(_translate("tickets_inter", "   7"))
        self.label_17.setText(_translate("tickets_inter", "   8"))
        self.label_18.setText(_translate("tickets_inter", "   9"))
        self.label_19.setText(_translate("tickets_inter", "- Cвободное"))
        self.label_20.setText(_translate("tickets_inter", "- Выбранное"))
        self.label_21.setText(_translate("tickets_inter", "- Занятое"))
        self.next_btn.setText(_translate("tickets_inter", "Далее"))
