# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_first_window(object):
    def setupUi(self, first_window):
        first_window.setObjectName("first_window")
        first_window.resize(1286, 582)
        first_window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(first_window)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 0, 1021, 471))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, -20, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 85, 255);")
        self.label.setObjectName("label")
        self.admin_btn = QtWidgets.QPushButton(self.centralwidget)
        self.admin_btn.setGeometry(QtCore.QRect(20, 470, 221, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.admin_btn.setFont(font)
        self.admin_btn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"border-style: outset;\n"
"color: white;\n"
"effect = QtWidgets.QGraphicsDropShadowEffect(QPushButton);\n"
"effect.setOffset(0, 0);\n"
"effect.setBlurRadius(20);\n"
"effect.setColor(QColor(57, 219, 255));\n"
"QPushButton.setGraphicsEffect(effect);\n"
"")
        self.admin_btn.setObjectName("admin_btn")
        first_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(first_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 26))
        self.menubar.setObjectName("menubar")
        first_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(first_window)
        self.statusbar.setObjectName("statusbar")
        first_window.setStatusBar(self.statusbar)

        self.retranslateUi(first_window)
        QtCore.QMetaObject.connectSlotsByName(first_window)

    def retranslateUi(self, first_window):
        _translate = QtCore.QCoreApplication.translate
        first_window.setWindowTitle(_translate("first_window", "MainWindow"))
        self.label.setText(_translate("first_window", "Выбор сеанса"))
        self.admin_btn.setText(_translate("first_window", "Авторизация администратора"))
